### ISSUE TITLE
Invalid Library Found in Documents/Arduino/libraries/ArduinoJWT-master

### ISSUE THREAD

**Issue by shabnamkousha** [yutter/ArduinoJWT#2]
Hi,

I am trying to use your Library, and when I try to add library through Arduino IDE/Library Manager, I get the following error:

"Invalid Library Found in Documents/Arduino/libraries/ArduinoJWT-master"

Can you help me with this issue?

Thanks,
Shab

**Comment by joaquinperaza** [comment]
Zip the src folder as ArduinoJWT.zip then try with that zip and should work
